### ISSUE TITLE
--lustre error on systems where lustre is read or write only

### ISSUE THREAD

**Issue by raphmur** [dagwieers/dstat#124]
On some systems, usually where lustre is slip in different volumes, or on badly installed volumes, some can be read only of write only. It throws an error while calling "dstat --lustre"

##### ISSUE TYPE

 - Bug Report

dstat-0.7.2

```
Dstat 0.7.2
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/dstat/

Platform posix/linux2
Kernel 2.6.32-573.26.1.el6.x86_64
Python 2.7.12 (default, Nov  8 2016, 11:30:02) 
[GCC 4.8.1]

Terminal type: xterm (color support)
Terminal size: 30 lines, 100 columns

Processors: 4
Pagesize: 4096
Clock ticks per secs: 100

internal:
	aio, cpu, cpu24, disk, disk24, disk24old, epoch, fs, int, int24, io, ipc, load, lock, mem, 
	net, page, page24, proc, raw, socket, swap, swapold, sys, tcp, time, udp, unix, vm
xxx/dstat-0.7.2/plugins:
	battery, battery-remain, cpufreq, dbus, disk-tps, disk-util, dstat, dstat-cpu, dstat-ctxt, 
	dstat-mem, fan, freespace, gpfs, gpfs-ops, helloworld, innodb-buffer, innodb-io, 
	innodb-ops, lustre, memcache-hits, mysql-io, 
	mysql-keys, mysql5-cmds, mysql5-conn, mysql5-io, mysql5-keys, net-packets, nfs3, nfs3-ops, 
	nfsd3, nfsd3-ops, ntp, postfix, power, proc-count, qmail, rpc, rpcd, sendmail, snooze, 
	squid, test, thermal, top-bio, top-bio-adv, top-childwait, top-cpu, top-cpu-adv, 
	top-cputime, top-cputime-avg, top-int, top-io, top-io-adv, top-latency, top-latency-avg, 
	top-mem, top-oom, utmp, vm-memctl, vmk-hba, vmk-int, vmk-nic, vz-cpu, vz-io, vz-ubc, wifi
```

##### OS / ENVIRONMENT

CentOS 6.7

##### STEPS TO REPRODUCE

On a system where the /proc/fs/lustre/llite/<name of lustre volume>/stats does not contain "read_bytes" and/or "write_bytes"

```
[user@machine ~]$ cat /proc/fs/lustre/llite/<name of lustre volume>/stats
snapshot_time             1479809998.740686 secs.usecs
read_bytes                1550 samples [bytes] 0 4194304 208110376
osc_read                  1505 samples [bytes] 3002 1048576 45406076
open                      2211 samples [regs]
close                     2211 samples [regs]
mmap                      3316 samples [regs]
seek                      28822 samples [regs]
readdir                   1389 samples [regs]
getattr                   11019599 samples [regs]
statfs                    10964818 samples [regs]
alloc_inode               9415 samples [regs]
getxattr                  654 samples [regs]
getxattr_hits             4 samples [regs]
inode_permission          3138741 samples [regs]

```

Call dstat --lustre

##### EXPECTED RESULTS

```
vol1             vol2           vol3
 read write: read write: read write
5.30B    0 : 920k  111k: 527k  138k
   0     0 :   0     0 :   0     0 
   0     0 :   0     0 :   0     0 
   0     0 :   0     0 :1390k 1229k
   0     0 :   0     0 :18.5M 18.4M
   0     0 :   0     0 : 122M  122M
   0     0 :   0     0 :46.0M 46.0M
   0     0 :   0     0 : 101M  101M
   0     0 :   0     0 : 104M  104M
   0     0 :   0     0 : 135M  135M
   0     0 :   0     0 : 122M  122M
   0     0 :   0     0 : 127M  127M
   0     0 :   0     0 : 104M  104M
   0     0 :   0     0 :81.8M 82.0M
   0     0 :   0     0 :95.3M 95.3M
   0     0 :   0     0 :   0     0 
   0     0 :   0     0 :   0     0 
```

##### ACTUAL RESULTS

```
[user@machine ~]$ dstat --lustre
Module dstat_lustre is still experimental.
Traceback (most recent call last):
  File "xxx/dstat-0.7.2/dstat", line 2554, in <module>
    main()
  File "xxx/dstat-0.7.2/dstat", line 2416, in main
    scheduler.run()
  File "xxx/python-2.7.12/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "xxx/dstat-0.7.2/dstat", line 2510, in perform
    o.extract()
  File "xxx/dstat-0.7.2/plugins/dstat_lustre.py", line 30, in extract
    self.set2[name] = (read, write)
UnboundLocalError: local variable 'write' referenced before assignment
```

**Comment by raphmur** [comment]
I have already prepared a commit with dstat_lustre.py by adding between lines 20 and 21

"
read = 0
write = 0
"

**Comment by brockpalen** [comment]
This will actually happen on any node that has not done any IO on the lustre mount.  

Lustre stat files do not include any stats where there is not at least 1 operation, rather than having a 0 counter.  (honestly, I find this annoying) 

Checking if they exist and if at the end setting values to zero would probably be an quick easy fix.
