### ISSUE TITLE
mstat.py doesn't work

### ISSUE THREAD

**Issue by kislyuk** [dagwieers/dstat#69]
`dstat/examples/mstat.py` doesn't work.

```
~/projects/dstat>./examples/mstat.py 
You did not select any stats, using -cdngy by default.
Traceback (most recent call last):
  File "./examples/mstat.py", line 35, in <module>
    title = title + '  ' + o.title()
  File "/mnt/DNAvertex/akislyuk/projects/dstat/examples/dstat.py", line 453, in title
    width = self.statwidth()
  File "/mnt/DNAvertex/akislyuk/projects/dstat/examples/dstat.py", line 441, in statwidth
    return len(self.nick) * self.colwidth() + len(self.nick) - 1
TypeError: object of type 'NoneType' has no len()
```

Also, the module shouldn't do stuff like print "You did not select any stats, using -cdngy by default." on import.

**Comment by dagwieers** [comment]
There is no real defined API interface, so changes in Dstat can easily break API consumers.
