### ISSUE TITLE
dstat --output breaks.

### ISSUE THREAD

**Issue by muyiibidun** [dagwieers/dstat#85]
**This used to work before. But suddenly, it started throwing the IndexError as shown below. This happened on a Xen VM running Ubuntu **

Traceback (most recent call last):
  File "/usr/bin/dstat", line 2554, in <module>
    main()
  File "/usr/bin/dstat", line 2416, in main
    scheduler.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/usr/bin/dstat", line 2514, in perform
    oline = oline + o.showcsv() + o.showcsvend(totlist, vislist)
  File "/usr/bin/dstat", line 542, in showcsvend
    if self is not vislist[-1]:
IndexError: list index out of range

**Comment by scottchiefbaker** [comment]
Is this still an issue? What dstat command are you running to generate this?

**Comment by dagwieers** [comment]
This is already fixed since some time and is related to #111.
