### ISSUE TITLE
dstat crash with --top-io-adv --output dstat.csv

### ISSUE THREAD

**Issue by pmazeris** [dagwieers/dstat#86]
Here is the error I get - Thank you

```
$ dstat -t --top-io-adv  --output dstat.csv
Traceback (most recent call last):
  File "/usr/bin/dstat", line 2554, in ?
    main()
  File "/usr/bin/dstat", line 2416, in main
    scheduler.run()
  File "/usr/lib64/python2.4/sched.py", line 105, in run
    void = action(*argument)
  File "/usr/bin/dstat", line 2514, in perform
    oline = oline + o.showcsv() + o.showcsvend(totlist, vislist)
  File "/usr/share/dstat/dstat_top_io_adv.py", line 75, in showcsv
    return self.val['i/o process'] + 'Top: %s\t%s\t%s\t%s' % (self.val['name'][0:self.width-20],      self.val['read_usage'], self.val['write_usage'], self.val['cpu_usage'])
KeyError: 'i/o process'


[root@ ~]$ python -V
Python 2.4.3
```

**Comment by scottchiefbaker** [comment]
I can confirm and recreate this.
